name: Ensure LICENSE in Root

on:
  push:
  workflow_dispatch:

jobs:
  add-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if LICENSE exists in repo root
        id: check_license
        run: |
          if [ -f LICENSE ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy LICENSE if missing
        if: steps.check_license.outputs.exists == 'false'
        run: |
          cp .github/LICENSE LICENSE
          git config user.name "iSpark Inno License Bot"
          git config user.email "no-reply@isparkinno.com"
          git add LICENSE
          git commit -m "Add standard LICENSE to root" || echo "LICENSE already present."
          git push
